export enum OrganisationType {
  BUYER = 'BUYER',
  EXPORTER = 'EXPORTER',
  FARMER = 'FARMER',
  COOPERATIVE = 'COOPERATIVE',
  LOGISTICS_PROVIDER = 'LOGISTICS_PROVIDER',
  BANK = 'BANK',
  INSURANCE = 'INSURANCE',
  GOVERNMENT = 'GOVERNMENT',
  CHAMBER_OF_COMMERCE = 'CHAMBER_OF_COMMERCE',
  OTHER = 'OTHER',
}

export enum OrganisationStatus {
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  REJECTED = 'REJECTED',
}

export enum VerificationStatus {
  UNVERIFIED = 'UNVERIFIED',
  PENDING = 'PENDING',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
}
