/** Fine-grained permissions used by RBAC guards. */
export enum Permission {
  USERS_READ = 'users:read',
  USERS_WRITE = 'users:write',
  USERS_INVITE = 'users:invite',
  ORG_READ = 'org:read',
  ORG_WRITE = 'org:write',
  ORG_MANAGE_MEMBERS = 'org:manage_members',
  ORG_MANAGE_ROLES = 'org:manage_roles',
  SETTINGS_READ = 'settings:read',
  SETTINGS_WRITE = 'settings:write',
  NOTIFICATIONS_READ = 'notifications:read',
  NOTIFICATIONS_WRITE = 'notifications:write',
  AUDIT_READ = 'audit:read',
  ACTIVITY_READ = 'activity:read',
  TRUST_READ = 'trust:read',
  TRUST_WRITE = 'trust:write',
  TRUST_REVIEW = 'trust:review',
  DOCUMENTS_READ = 'documents:read',
  DOCUMENTS_WRITE = 'documents:write',
  REGISTRY_READ = 'registry:read',
  TRADE_READ = 'trade:read',
  TRADE_WRITE = 'trade:write',
  COMPLIANCE_READ = 'compliance:read',
  COMPLIANCE_WRITE = 'compliance:write',
  COMPLIANCE_REVIEW = 'compliance:review',
  FINANCE_READ = 'finance:read',
  FINANCE_WRITE = 'finance:write',
  FINANCE_OPERATE = 'finance:operate',
  LOGISTICS_READ = 'logistics:read',
  LOGISTICS_WRITE = 'logistics:write',
  LOGISTICS_OPERATE = 'logistics:operate',
  ANALYTICS_READ = 'analytics:read',
  AI_READ = 'ai:read',
  AI_WRITE = 'ai:write',
  ADMIN_ALL = 'admin:all',
}

const TRUST_BASE = [
  Permission.TRUST_READ,
  Permission.TRUST_WRITE,
  Permission.DOCUMENTS_READ,
  Permission.DOCUMENTS_WRITE,
  Permission.REGISTRY_READ,
] as const;

const TRADE_BASE = [Permission.TRADE_READ, Permission.TRADE_WRITE] as const;

const COMPLIANCE_BASE = [
  Permission.COMPLIANCE_READ,
  Permission.COMPLIANCE_WRITE,
] as const;

const FINANCE_BASE = [
  Permission.FINANCE_READ,
  Permission.FINANCE_WRITE,
] as const;

const LOGISTICS_BASE = [
  Permission.LOGISTICS_READ,
  Permission.LOGISTICS_WRITE,
] as const;

const ANALYTICS_BASE = [Permission.ANALYTICS_READ] as const;

const AI_BASE = [Permission.AI_READ, Permission.AI_WRITE] as const;

export const ROLE_PERMISSIONS: Record<string, Permission[]> = {
  SYSTEM_ADMIN: [Permission.ADMIN_ALL],
  BUYER: [
    Permission.ORG_READ,
    Permission.ORG_WRITE,
    Permission.USERS_READ,
    Permission.SETTINGS_READ,
    Permission.SETTINGS_WRITE,
    Permission.NOTIFICATIONS_READ,
    Permission.ACTIVITY_READ,
    ...TRUST_BASE,
    ...TRADE_BASE,
    ...COMPLIANCE_BASE,
    ...FINANCE_BASE,
    ...LOGISTICS_BASE,
    ...ANALYTICS_BASE,
    ...AI_BASE,
  ],
  EXPORTER: [
    Permission.ORG_READ,
    Permission.ORG_WRITE,
    Permission.USERS_READ,
    Permission.SETTINGS_READ,
    Permission.SETTINGS_WRITE,
    Permission.NOTIFICATIONS_READ,
    Permission.ACTIVITY_READ,
    ...TRUST_BASE,
    ...TRADE_BASE,
    ...COMPLIANCE_BASE,
    ...FINANCE_BASE,
    ...LOGISTICS_BASE,
    ...ANALYTICS_BASE,
    ...AI_BASE,
  ],
  FARMER: [
    Permission.ORG_READ,
    Permission.SETTINGS_READ,
    Permission.SETTINGS_WRITE,
    Permission.NOTIFICATIONS_READ,
    Permission.ACTIVITY_READ,
    Permission.TRUST_READ,
    Permission.DOCUMENTS_READ,
    Permission.DOCUMENTS_WRITE,
    Permission.REGISTRY_READ,
    Permission.TRADE_READ,
    Permission.COMPLIANCE_READ,
    Permission.FINANCE_READ,
    Permission.LOGISTICS_READ,
    Permission.ANALYTICS_READ,
    Permission.AI_READ,
  ],
  COOPERATIVE: [
    Permission.ORG_READ,
    Permission.ORG_WRITE,
    Permission.USERS_READ,
    Permission.USERS_INVITE,
    Permission.ORG_MANAGE_MEMBERS,
    Permission.SETTINGS_READ,
    Permission.SETTINGS_WRITE,
    Permission.NOTIFICATIONS_READ,
    Permission.ACTIVITY_READ,
    ...TRUST_BASE,
    ...TRADE_BASE,
    ...COMPLIANCE_BASE,
    ...FINANCE_BASE,
    ...LOGISTICS_BASE,
    ...ANALYTICS_BASE,
    ...AI_BASE,
  ],
  LOGISTICS_PROVIDER: [
    Permission.ORG_READ,
    Permission.ORG_WRITE,
    Permission.USERS_READ,
    Permission.SETTINGS_READ,
    Permission.SETTINGS_WRITE,
    Permission.NOTIFICATIONS_READ,
    Permission.ACTIVITY_READ,
    ...TRUST_BASE,
    Permission.TRADE_READ,
    Permission.COMPLIANCE_READ,
    Permission.LOGISTICS_READ,
    Permission.LOGISTICS_WRITE,
    Permission.LOGISTICS_OPERATE,
    Permission.ANALYTICS_READ,
    Permission.AI_READ,
  ],
  BANK: [
    Permission.ORG_READ,
    Permission.ORG_WRITE,
    Permission.USERS_READ,
    Permission.SETTINGS_READ,
    Permission.SETTINGS_WRITE,
    Permission.NOTIFICATIONS_READ,
    Permission.AUDIT_READ,
    Permission.ACTIVITY_READ,
    Permission.TRUST_READ,
    Permission.DOCUMENTS_READ,
    Permission.REGISTRY_READ,
    Permission.TRADE_READ,
    Permission.COMPLIANCE_READ,
    Permission.FINANCE_READ,
    Permission.FINANCE_WRITE,
    Permission.FINANCE_OPERATE,
    Permission.ANALYTICS_READ,
    ...AI_BASE,
  ],
  INSURANCE: [
    Permission.ORG_READ,
    Permission.ORG_WRITE,
    Permission.USERS_READ,
    Permission.SETTINGS_READ,
    Permission.SETTINGS_WRITE,
    Permission.NOTIFICATIONS_READ,
    Permission.ACTIVITY_READ,
    Permission.TRUST_READ,
    Permission.DOCUMENTS_READ,
    Permission.REGISTRY_READ,
    Permission.TRADE_READ,
    Permission.COMPLIANCE_READ,
    Permission.FINANCE_READ,
    Permission.LOGISTICS_READ,
    Permission.ANALYTICS_READ,
    Permission.AI_READ,
  ],
  GOVERNMENT_OFFICER: [
    Permission.ORG_READ,
    Permission.USERS_READ,
    Permission.AUDIT_READ,
    Permission.ACTIVITY_READ,
    Permission.NOTIFICATIONS_READ,
    Permission.SETTINGS_READ,
    Permission.TRUST_READ,
    Permission.TRUST_REVIEW,
    Permission.DOCUMENTS_READ,
    Permission.REGISTRY_READ,
    Permission.TRADE_READ,
    Permission.COMPLIANCE_READ,
    Permission.COMPLIANCE_REVIEW,
    Permission.FINANCE_READ,
    Permission.LOGISTICS_READ,
    Permission.ANALYTICS_READ,
    Permission.AI_READ,
  ],
  CHAMBER_OF_COMMERCE: [
    Permission.ORG_READ,
    Permission.USERS_READ,
    Permission.AUDIT_READ,
    Permission.ACTIVITY_READ,
    Permission.NOTIFICATIONS_READ,
    Permission.SETTINGS_READ,
    Permission.TRUST_READ,
    Permission.DOCUMENTS_READ,
    Permission.REGISTRY_READ,
    Permission.TRADE_READ,
    Permission.COMPLIANCE_READ,
    Permission.COMPLIANCE_REVIEW,
    Permission.FINANCE_READ,
    Permission.LOGISTICS_READ,
    Permission.ANALYTICS_READ,
    Permission.AI_READ,
  ],
};

export function roleHasPermission(
  role: string,
  permission: Permission,
): boolean {
  const perms = ROLE_PERMISSIONS[role] ?? [];
  return perms.includes(Permission.ADMIN_ALL) || perms.includes(permission);
}
